spring:
  application:
    name: trading
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yt_trading
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver

server:
  port: 5455
